### PR TITLE
[BUGFIX] remove file after being moved

### PR DESCRIPTION
**Pull request by BlazeIsHere**

### CODE REVIEW

**Comment by newLoki** [comment]
@BlazeIsHere Hi, unfortunately @tobi812 is sick this week but he will have a look next week.

Maybe you can give us a little explanation what exactly is the problem you've fixed here.

**Comment by BlazeIsHere** [comment]
Hi. This is about files (pdfs mainly) not being removed after they have 
been created in temp folders and copied later to the destination folders.

**Comment by tobi812** [comment]
In my Opinion, it seems to be a Bug indeed. So when you have tested it @BlazeIsHere, it should be fine.

**Comment by BlazeIsHere** [comment]
Tested locally. Success.

**Comment by tobi812** [comment]
@newLoki In my opinion it looks fine, and as it is an urgent fix, i'will merge the change.

**Comment by BlazeIsHere** [comment]
Hi Tobi, 
can you tag it please ?
Thanks! :)

**Comment by tobi812** [comment]
Already done -> 0.2.1

**Pull request merged**
